version: '3'

services:
  mysql-docker:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'api'
      MYSQL_USER: 'spring'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-docker-data:/var/lib/mysql

  poc-api:
    image: 'regissantana/api-poc:${TAG}'
    environment:
      - "SPRING_PROFILES_ACTIVE=${TAG}"
    ports:
      - '6081:8081'
    depends_on:
      - mysql-docker

volumes:
  mysql-docker-data:
