spring:
  datasource:
    url: jdbc:mysql://mysql-docker:3306/api
    username: spring
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate.temp:
        use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: 8081
  undertow:
    ioThreads: 15
    workerThreads: 150
    accesslog:
      enabled: true
  compression:
    enabled: true
    mimeTypes: text/xml, text/css, text/html, application/json
    minResponseSize: 4096
  servlet:
    context-path: /poc-api

logging:
  level:
    root: INFO
  path: ./log
  file:
    max-size: 100MB
    max-history: 2

token:
  signature: 123456



