spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/camunda
    username: root
    password: root
  jpa:
    properties:
      hibernate.temp:
        use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true

server:
  port: 8081
  undertow:
    ioThreads: 15
    workerThreads: 150
    accesslog:
      enabled: true
  compression:
    enabled: true
    mimeTypes: text/xml, text/css, text/html, application/json
    minResponseSize: 4096
#
#spring:
#  jersey:
#    application-path: /
#logging:
#  level: trace

token:
  signature: 123456
