spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring
    username: spring
    password: password
  jpa:
    properties:
      hibernate.temp:
        use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true

server:
  port: 8081
  undertow:
    ioThreads: 15
    workerThreads: 150
    accesslog:
      enabled: true
  compression:
    enabled: true
    mimeTypes: text/xml, text/css, text/html, application/json
    minResponseSize: 4096
  servlet:
    context-path: /spring-example

logging:
  level:
    root: INFO
  path: ./log
  file:
    max-size: 100MB
    max-history: 2

token:
  signature: 123456



