version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'spring'
      MYSQL_USER: 'spring'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  spring-example:
    image: 'regissantana/spring-example:${TAG}'
    environment:
      - "SPRING_PROFILES_ACTIVE=${TAG}"
    ports:
      - '6080:8081'
    depends_on:
      - db

volumes:
  my-db: